apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"nginx-ingress-app-protect-dos"},"rules":[{"apiGroups":["appprotectdos.f5.com"],"resources":["apdospolicies","apdoslogconfs","dosprotectedresources"],"verbs":["get","watch","list"]}]}
    name: nginx-ingress-app-protect-dos
  rules:
  - apiGroups:
    - appprotectdos.f5.com
    resources:
    - apdospolicies
    - apdoslogconfs
    - dosprotectedresources
    verbs:
    - get
    - watch
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"nginx-ingress-app-protect-dos"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"nginx-ingress-app-protect-dos"},"subjects":[{"kind":"ServiceAccount","name":"nginx-ingress","namespace":"nginx-ingress"}]}
    name: nginx-ingress-app-protect-dos
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: nginx-ingress-app-protect-dos
  subjects:
  - kind: ServiceAccount
    name: nginx-ingress
    namespace: nginx-ingress
kind: List
metadata: {}
